#!/bin/zsh

pidof clion;

if [[ $? -ne 0 ]]; then
	notify-send --app-name="clion:// handler" --icon="error" "CLion is not running, not opening file"
	exit;
fi

file=$(echo "$1" | sed -E 's/.*file=([^&]+).*/\1/');
line=$(echo "$1" | sed -E 's/.*line=([^&]+).*/\1/');

if [[ -z "file" ]]; then
	exit;
fi

if [[ "$line" == "$1" ]]; then
	line="1";
fi

$HOME/.local/binaries/clion/bin/clion --line "$line" "$file"
