# list of options: https://github.com/CachyOS/proton-cachyos

# STEAM_COMPAT_CONFIG
# example STEAM_COMPAT_CONFIG="key1=value1,key2=value2"

PROTON_USE_NTSYNC=1
PROTON_DXVK_LOWLATENCY=1
PROTON_XESS_UPGRADE=1
# this works on modern cards. RDNA2 has problems.
# PROTON_FSR4_UPGRADE=1

# enable per game. This can cause issues.
# update: fuck it, we ball
# unset via: env --unset=PROTON_ENABLE_WAYLAND %command% or env -u PROTON_ENABLE_WAYLAND %command%
PROTON_ENABLE_WAYLAND=1

PROTON_ENABLE_HDR=1
