user_pref("browser.ml.chat.enabled", false)
user_pref("browser.ml.chat.menu", false)
user_pref("browser.ml.chat.page", false)
user_pref("browser.ml.chat.page.footerBadge", false)
user_pref("browser.ml.chat.page.menuBadge", false)
user_pref("browser.ml.chat.shortcuts", false)
user_pref("browser.ml.chat.shortcuts.custom", false)
user_pref("browser.ml.enable", false)
user_pref("browser.ml.linkPreview.collapsed", true)
user_pref("browser.ml.linkPreview.enabled", false)
user_pref("browser.ml.pageAssist.enabled", false);
user_pref("browser.ml.smartAssist.enabled", false);
user_pref("browser.search.visualSearch.featureGate", false);
user_pref("browser.tabs.groups.smart.enabled", false);
user_pref("browser.tabs.groups.smart.userEnabled", false)
user_pref("browser.urlbar.quicksuggest.mlEnabled", false);
user_pref("extensions.ml.enabled", false);
user_pref("full-screen-api.transition.timeout", 0)
user_pref("full-screen-api.warning.delay", 0)
user_pref("full-screen-api.warning.timeout", 0)
user_pref("layout.css.devPixelsPerPx", 1.1)
user_pref("pdfjs.enableAltText", false);
user_pref("places.semanticHistory.featureGate", false);
user_pref("sidebar.revamp", false);
user_pref("sidebar.visibility", "hide-sidebar")
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("widget.use-xdg-desktop-portal", true)
user_pref("widget.use-xdg-desktop-portal.file-picker", 1)
user_pref("widget.use-xdg-desktop-portal.mime-handler", 1)
